### ISSUE TITLE
nice project - have a look at the Lab color space

### ISSUE THREAD

**Issue by fdietze** [26c8/colort#1]
You might be interested in doing color tinting, adjustments, interpolation, or manipulation in general in the [Lab color space](https://en.wikipedia.org/wiki/Lab_color_space). I like especially the HCL representation which works like HSV. Once I understood this color space, RGB calculations feel completely wrong and ugly ;).
It works like this:
Convert RGB to Lab -> do your calculations -> Convert back to RGB

**Comment by neeasade** [comment]
Currently out of scope -- I see it as a 'where does it end' type of thing, at least for this tool. Were I to target other color spaces, I would want to handle factors there and such, and right now the source for this guy is pretty small. I was originally looking into `ciecam02`, which was a bit overwhelming for someone just looking into all these color things, so when I do feel like getting more advanced I will return to this issue for reference. 

If you are looking for better color options though, might want to take a look at https://github.com/baskerville/ciecam02

**Comment by fdietze** [comment]
Of course. This was not a request - more a hint for the curious mind. Good luck!

**Comment by neeasade** [comment]
Yepp, thanks for the input :)

**Comment by neeasade** [comment]
Want to leave a comment here for any future spelunkers. colorspace exploration culminated in experiments built on top of emacs color.el (many notes within): [color tools](https://github.com/neeasade/emacs.d/blob/d713b16f6e860c80424bc327967d8e549fe42301/lisp/trees/colors.el) - [theme](https://github.com/neeasade/emacs.d/blob/d713b16f6e860c80424bc327967d8e549fe42301/lisp/themes/neea-theme.el)

edit: and a blog post: https://notes.neeasade.net/color-spaces.html
