### ISSUE TITLE
Colort sometimes returns wrong color

### ISSUE THREAD

**Issue by tudurom** [26c8/colort#2]
![screenshot](https://my.mixtape.moe/mnmycy.png)

**Comment by neeasade** [comment]
what is your shell? 

tried to reproduce with this:
``` sh
#!/usr/bin/env bash

input="#021b21"
correct="#162F35"

for test in {0..1000}; do
        [ "$correct" = "$(colort +20 $input)" ] || echo ding
done
```

**Comment by tudurom** [comment]
With the following script, using bash, I got some random results:

```bash
#!/usr/bin/env bash

input="#021b21"
correct="#162F35"

for test in {0..1000}; do
        [ "$correct" = "$(colort +20 $input)" ] || echo ding
done | wc -l
```

```
58
60
60
60
83
55
```

It worked normally on my old laptop, I really hope that it's not related to the fact that my current PC has a ryzen cpu

**Comment by tudurom** [comment]
Compiling with clang solved the issue. I will make a PR with some Makefile changes. It looks like it's GCC's fault.
