### ISSUE TITLE
Strange results when parsing input

### ISSUE THREAD

**Issue by apiraino** [26c8/colort#4]
I have strange results a valid my `.Xresources` file, example I have background defined as:

```
#define black #2c2e34
*.background:   black
```

`colort` gives me

```
$ colort background && echo
back000000
$ colort -s 1 background && echo
bAC0000und
$ colort -s 2 background && echo
ba0C0000nd
$ colort -s 3 background && echo
bac000000d
$ colort -s 4 background && echo
back000000
$ colort -s 6 background && echo
backgr000000HELL=/bin/bash
$ colort -s 8 background && echo
backgrou000000LL=/bin/bash
$ colort -s 12 background && echo
background
$ colort -s 14 background && echo
background
```
or

```
$ colort -s 10 background && echo
background000000=/bin/bash
```

not to mention what it looks like a memory bug.

An opinion on this?

thanks

**Comment by neeasade** [comment]
colort doesn't have Xresources integration -- you need to pass it a color to act on, not an Xresources key (eg `colort 1 2c2e34`). You can use something like [xrq](https://github.com/arianon/xrq) to get the background value

**Comment by apiraino** [comment]
ah you're right, sorry (late night dumb question).

Still, I think there are some issues in the input parsing (e.g. missing `"` around the rgb triplet fails) or that weird output I pointed before. 

I'll rename and leave this issue open in case you want to investigate, else feel free to close

**Comment by neeasade** [comment]
all good! thanks, but going to close -- the `-s` arg always looks 6 chars in front of where you specify, and it's not validated, so that's why the memory issue occurs -- and re: `"`, I believe that's due `#` being a comment in most shells, so you need to escape it or use single quotes
